In [1]:
import numpy as np

## Creating numpy array
### From python list


In [2]:
my_list = [1,2,3]
type(my_list)

list

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_list2=[4,5,6]
array1= np.array(my_list)
array2=np.array(my_list2)
print(array1+array2)
print(my_list+my_list2)

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [5]:
# matrix
lol=[[1,2,3],[4,5,6],[7,8,9]]
lol2=[[7,8,9],[10,11,12]]
matrix_a=np.array(lol)
matrix_b=np.array(lol2)

In [6]:
matrix_a+lol

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Build in method = arrange

In [7]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
y=np.arange(0,15,3)
y

array([ 0,  3,  6,  9, 12])

In [9]:
x.dtype

dtype('int32')

In [10]:
x[0::2]

array([0, 2, 4, 6, 8])

In [11]:
x[1::2]

array([1, 3, 5, 7, 9])

In [12]:
arr_2d=np.array([[11, 14, 14],[15, 11, 18],[18, 12, 15]])

a=arr_2d[:2,:3]
b=arr_2d[1:3,:2]
c=arr_2d[1:3,1:3]
print(a)
print(b)
print(c)

[[11 14 14]
 [15 11 18]]
[[15 11]
 [18 12]]
[[11 18]
 [12 15]]


In [13]:
arr1d = np.zeros(10)
print(len(arr1d))

10


In [14]:
arr2d=np.zeros((15,10))
print(len(arr2d))

15


# Selection

In [15]:
gaji = np.random.randint(5,25,20)
gaji

array([ 8,  6, 12, 19,  7, 21, 15, 17,  7, 12, 13, 18, 22, 19, 20,  8,  7,
        5, 11, 14])

In [16]:
## Selection gaji karyawan di atas 10 jt
gaji>10

array([False, False,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True])

In [17]:
up_10=gaji[gaji>10]
len(up_10)

13

# Aritmatik

In [18]:
x= np.arange(5,15)
y=np.arange(15,25)


In [19]:
np.sqrt(25**2)

25.0

In [20]:
np.log(8)

2.0794415416798357

### Quiz

In [21]:
x=np.arange(1,11)

In [49]:
y=x.reshape(2,5)
z=x.reshape(5,2)
a=y[:3,:3]
b=x[(x%2)==1]
c=x[0:5].reshape(5,1)
print(y, '\n\n',z,'\n\n',a,'\n\n',b,'\n\n', c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

 [[1 2 3]
 [6 7 8]] 

 [1 3 5 7 9] 

 [[1]
 [2]
 [3]
 [4]
 [5]]


# size of array

In [50]:
x.size

10

# Data Type

In [51]:
x.dtype

dtype('int32')

# item size (Bytes)

In [52]:
x.itemsize

4

# Linear Aljabar

2x+y=5
x+y=7
maka berapa x dan y

In [55]:
a=np.array([[2,1],[1,1]])
b=np.array([5,7])
x,y=np.linalg.solve(a,b)
print(x,y)

-2.0 9.0


In [56]:
a=np.array([[4,7],[3,2]])
b=np.array([2,-5])
x,y=np.linalg.solve(a,b)
print(x,y)

-3.0 2.0


### Soal

In [58]:
a=np.array([[1,1],[4,2]])
b=np.array([25,70])
c=np.array([[2,1,1],[1,2,1],[3,2,1]])
d=np.array([4700,4300,7100])
e,f,g=np.linalg.solve(c,d)
x,y=np.linalg.solve(a,b)
print(f'kambing berjumlah {x} dan ayam berjumlah {y}')
print(f'harga satu buku {e}, harga satu pensil {f}, dan harga satu penghapus {g}')

kambing berjumlah 10.0 dan ayam berjumlah 15.0
harga satu buku 1400.0, harga satu pensil 999.9999999999999, dan harga satu penghapus 900.0000000000002


In [ ]:
np.vstack